operator:
  image:
    repository: ""
    version: ""
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi
rbacProxy:
  image:
    repository: "cbartifactory/kube-rbac-proxy"
    version: "v0.15.0-containers-feb-24"
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 20m
      memory: 16Mi
operatorNamespace: "cbcontainers-dataplane"
createOperatorNamespace: true
installCRD: true
