# This patch inject a sidecar container which is a HTTP proxy for the
# controller manager, it performs RBAC authorization against the Kubernetes API using SubjectAccessReviews.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: kube-rbac-proxy
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        args:
        - "--secure-listen-address=0.0.0.0:8443"
        - "--upstream=http://127.0.0.1:8080/"
        - "--logtostderr=true"
        - "--v=10"
        ports:
        - containerPort: 8443
          name: https
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 20m
            memory: 16Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          # See below on the source of this UID
          # https://github.com/GoogleContainerTools/distroless/blob/main/base/base.bzl#L7
          # https://github.com/brancz/kube-rbac-proxy/pull/85
          runAsUser: 65532
          runAsNonRoot: true
      - name: manager
        args:
        - "--health-probe-bind-address=:8081"
        - "--metrics-bind-address=127.0.0.1:8080"
