//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersAgent) DeepCopyInto(out *CBContainersAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersAgent.
func (in *CBContainersAgent) DeepCopy() *CBContainersAgent {
	if in == nil {
		return nil
	}
	out := new(CBContainersAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CBContainersAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersAgentList) DeepCopyInto(out *CBContainersAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CBContainersAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersAgentList.
func (in *CBContainersAgentList) DeepCopy() *CBContainersAgentList {
	if in == nil {
		return nil
	}
	out := new(CBContainersAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CBContainersAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersAgentSpec) DeepCopyInto(out *CBContainersAgentSpec) {
	*out = *in
	in.Gateways.DeepCopyInto(&out.Gateways)
	in.Components.DeepCopyInto(&out.Components)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersAgentSpec.
func (in *CBContainersAgentSpec) DeepCopy() *CBContainersAgentSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersAgentStatus) DeepCopyInto(out *CBContainersAgentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersAgentStatus.
func (in *CBContainersAgentStatus) DeepCopy() *CBContainersAgentStatus {
	if in == nil {
		return nil
	}
	out := new(CBContainersAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersApiGatewaySpec) DeepCopyInto(out *CBContainersApiGatewaySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersApiGatewaySpec.
func (in *CBContainersApiGatewaySpec) DeepCopy() *CBContainersApiGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersApiGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersBasicSpec) DeepCopyInto(out *CBContainersBasicSpec) {
	*out = *in
	in.Monitor.DeepCopyInto(&out.Monitor)
	in.Enforcer.DeepCopyInto(&out.Enforcer)
	in.StateReporter.DeepCopyInto(&out.StateReporter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersBasicSpec.
func (in *CBContainersBasicSpec) DeepCopy() *CBContainersBasicSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersBasicSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersClusterScannerAgentSpec) DeepCopyInto(out *CBContainersClusterScannerAgentSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DaemonSetAnnotations != nil {
		in, out := &in.DaemonSetAnnotations, &out.DaemonSetAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodTemplateAnnotations != nil {
		in, out := &in.PodTemplateAnnotations, &out.PodTemplateAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Image.DeepCopyInto(&out.Image)
	in.Resources.DeepCopyInto(&out.Resources)
	out.Probes = in.Probes
	in.Prometheus.DeepCopyInto(&out.Prometheus)
	out.K8sContainerEngine = in.K8sContainerEngine
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersClusterScannerAgentSpec.
func (in *CBContainersClusterScannerAgentSpec) DeepCopy() *CBContainersClusterScannerAgentSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersClusterScannerAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersClusterScanningSpec) DeepCopyInto(out *CBContainersClusterScanningSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.ImageScanningReporter.DeepCopyInto(&out.ImageScanningReporter)
	in.ClusterScannerAgent.DeepCopyInto(&out.ClusterScannerAgent)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersClusterScanningSpec.
func (in *CBContainersClusterScanningSpec) DeepCopy() *CBContainersClusterScanningSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersClusterScanningSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersCndrSensorSpec) DeepCopyInto(out *CBContainersCndrSensorSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DaemonSetAnnotations != nil {
		in, out := &in.DaemonSetAnnotations, &out.DaemonSetAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodTemplateAnnotations != nil {
		in, out := &in.PodTemplateAnnotations, &out.PodTemplateAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Image.DeepCopyInto(&out.Image)
	in.Resources.DeepCopyInto(&out.Resources)
	in.Prometheus.DeepCopyInto(&out.Prometheus)
	if in.VerbosityLevel != nil {
		in, out := &in.VerbosityLevel, &out.VerbosityLevel
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersCndrSensorSpec.
func (in *CBContainersCndrSensorSpec) DeepCopy() *CBContainersCndrSensorSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersCndrSensorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersCndrSpec) DeepCopyInto(out *CBContainersCndrSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.Sensor.DeepCopyInto(&out.Sensor)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersCndrSpec.
func (in *CBContainersCndrSpec) DeepCopy() *CBContainersCndrSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersCndrSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersCommonProbesSpec) DeepCopyInto(out *CBContainersCommonProbesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersCommonProbesSpec.
func (in *CBContainersCommonProbesSpec) DeepCopy() *CBContainersCommonProbesSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersCommonProbesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersComponentsSettings) DeepCopyInto(out *CBContainersComponentsSettings) {
	*out = *in
	if in.DaemonSetsTolerations != nil {
		in, out := &in.DaemonSetsTolerations, &out.DaemonSetsTolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreateDefaultImagePullSecrets != nil {
		in, out := &in.CreateDefaultImagePullSecrets, &out.CreateDefaultImagePullSecrets
		*out = new(bool)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersComponentsSettings.
func (in *CBContainersComponentsSettings) DeepCopy() *CBContainersComponentsSettings {
	if in == nil {
		return nil
	}
	out := new(CBContainersComponentsSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersComponentsSpec) DeepCopyInto(out *CBContainersComponentsSpec) {
	*out = *in
	in.Basic.DeepCopyInto(&out.Basic)
	in.RuntimeProtection.DeepCopyInto(&out.RuntimeProtection)
	if in.Cndr != nil {
		in, out := &in.Cndr, &out.Cndr
		*out = new(CBContainersCndrSpec)
		(*in).DeepCopyInto(*out)
	}
	in.ClusterScanning.DeepCopyInto(&out.ClusterScanning)
	in.Settings.DeepCopyInto(&out.Settings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersComponentsSpec.
func (in *CBContainersComponentsSpec) DeepCopy() *CBContainersComponentsSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersComponentsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersEnforcerSpec) DeepCopyInto(out *CBContainersEnforcerSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DeploymentAnnotations != nil {
		in, out := &in.DeploymentAnnotations, &out.DeploymentAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodTemplateAnnotations != nil {
		in, out := &in.PodTemplateAnnotations, &out.PodTemplateAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ReplicasCount != nil {
		in, out := &in.ReplicasCount, &out.ReplicasCount
		*out = new(int32)
		**out = **in
	}
	in.Prometheus.DeepCopyInto(&out.Prometheus)
	in.Image.DeepCopyInto(&out.Image)
	in.Resources.DeepCopyInto(&out.Resources)
	out.Probes = in.Probes
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableEnforcementFeature != nil {
		in, out := &in.EnableEnforcementFeature, &out.EnableEnforcementFeature
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersEnforcerSpec.
func (in *CBContainersEnforcerSpec) DeepCopy() *CBContainersEnforcerSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersEnforcerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersEventsGatewaySpec) DeepCopyInto(out *CBContainersEventsGatewaySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersEventsGatewaySpec.
func (in *CBContainersEventsGatewaySpec) DeepCopy() *CBContainersEventsGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersEventsGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersFileProbesSpec) DeepCopyInto(out *CBContainersFileProbesSpec) {
	*out = *in
	out.CBContainersCommonProbesSpec = in.CBContainersCommonProbesSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersFileProbesSpec.
func (in *CBContainersFileProbesSpec) DeepCopy() *CBContainersFileProbesSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersFileProbesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersGatewayTLS) DeepCopyInto(out *CBContainersGatewayTLS) {
	*out = *in
	if in.RootCAsBundle != nil {
		in, out := &in.RootCAsBundle, &out.RootCAsBundle
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersGatewayTLS.
func (in *CBContainersGatewayTLS) DeepCopy() *CBContainersGatewayTLS {
	if in == nil {
		return nil
	}
	out := new(CBContainersGatewayTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersGatewaysSpec) DeepCopyInto(out *CBContainersGatewaysSpec) {
	*out = *in
	in.GatewayTLS.DeepCopyInto(&out.GatewayTLS)
	out.ApiGateway = in.ApiGateway
	out.CoreEventsGateway = in.CoreEventsGateway
	out.HardeningEventsGateway = in.HardeningEventsGateway
	out.RuntimeEventsGateway = in.RuntimeEventsGateway
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersGatewaysSpec.
func (in *CBContainersGatewaysSpec) DeepCopy() *CBContainersGatewaysSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersGatewaysSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersHTTPProbesSpec) DeepCopyInto(out *CBContainersHTTPProbesSpec) {
	*out = *in
	out.CBContainersCommonProbesSpec = in.CBContainersCommonProbesSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersHTTPProbesSpec.
func (in *CBContainersHTTPProbesSpec) DeepCopy() *CBContainersHTTPProbesSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersHTTPProbesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersImageScanningReporterSpec) DeepCopyInto(out *CBContainersImageScanningReporterSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DeploymentAnnotations != nil {
		in, out := &in.DeploymentAnnotations, &out.DeploymentAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodTemplateAnnotations != nil {
		in, out := &in.PodTemplateAnnotations, &out.PodTemplateAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ReplicasCount != nil {
		in, out := &in.ReplicasCount, &out.ReplicasCount
		*out = new(int32)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Image.DeepCopyInto(&out.Image)
	in.Resources.DeepCopyInto(&out.Resources)
	out.Probes = in.Probes
	in.Prometheus.DeepCopyInto(&out.Prometheus)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersImageScanningReporterSpec.
func (in *CBContainersImageScanningReporterSpec) DeepCopy() *CBContainersImageScanningReporterSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersImageScanningReporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersImageSpec) DeepCopyInto(out *CBContainersImageSpec) {
	*out = *in
	if in.PullSecrets != nil {
		in, out := &in.PullSecrets, &out.PullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersImageSpec.
func (in *CBContainersImageSpec) DeepCopy() *CBContainersImageSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersMonitorSpec) DeepCopyInto(out *CBContainersMonitorSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DeploymentAnnotations != nil {
		in, out := &in.DeploymentAnnotations, &out.DeploymentAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodTemplateAnnotations != nil {
		in, out := &in.PodTemplateAnnotations, &out.PodTemplateAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Image.DeepCopyInto(&out.Image)
	in.Resources.DeepCopyInto(&out.Resources)
	out.Probes = in.Probes
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersMonitorSpec.
func (in *CBContainersMonitorSpec) DeepCopy() *CBContainersMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersPrometheusSpec) DeepCopyInto(out *CBContainersPrometheusSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersPrometheusSpec.
func (in *CBContainersPrometheusSpec) DeepCopy() *CBContainersPrometheusSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersPrometheusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersRuntimeProtectionSpec) DeepCopyInto(out *CBContainersRuntimeProtectionSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.Resolver.DeepCopyInto(&out.Resolver)
	in.Sensor.DeepCopyInto(&out.Sensor)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersRuntimeProtectionSpec.
func (in *CBContainersRuntimeProtectionSpec) DeepCopy() *CBContainersRuntimeProtectionSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersRuntimeProtectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersRuntimeResolverSpec) DeepCopyInto(out *CBContainersRuntimeResolverSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DeploymentAnnotations != nil {
		in, out := &in.DeploymentAnnotations, &out.DeploymentAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodTemplateAnnotations != nil {
		in, out := &in.PodTemplateAnnotations, &out.PodTemplateAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ReplicasCount != nil {
		in, out := &in.ReplicasCount, &out.ReplicasCount
		*out = new(int32)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Image.DeepCopyInto(&out.Image)
	in.Resources.DeepCopyInto(&out.Resources)
	out.Probes = in.Probes
	in.Prometheus.DeepCopyInto(&out.Prometheus)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersRuntimeResolverSpec.
func (in *CBContainersRuntimeResolverSpec) DeepCopy() *CBContainersRuntimeResolverSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersRuntimeResolverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersRuntimeSensorSpec) DeepCopyInto(out *CBContainersRuntimeSensorSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DaemonSetAnnotations != nil {
		in, out := &in.DaemonSetAnnotations, &out.DaemonSetAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodTemplateAnnotations != nil {
		in, out := &in.PodTemplateAnnotations, &out.PodTemplateAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Image.DeepCopyInto(&out.Image)
	in.Resources.DeepCopyInto(&out.Resources)
	out.Probes = in.Probes
	in.Prometheus.DeepCopyInto(&out.Prometheus)
	if in.VerbosityLevel != nil {
		in, out := &in.VerbosityLevel, &out.VerbosityLevel
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersRuntimeSensorSpec.
func (in *CBContainersRuntimeSensorSpec) DeepCopy() *CBContainersRuntimeSensorSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersRuntimeSensorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersStateReporterSpec) DeepCopyInto(out *CBContainersStateReporterSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DeploymentAnnotations != nil {
		in, out := &in.DeploymentAnnotations, &out.DeploymentAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodTemplateAnnotations != nil {
		in, out := &in.PodTemplateAnnotations, &out.PodTemplateAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Image.DeepCopyInto(&out.Image)
	in.Resources.DeepCopyInto(&out.Resources)
	out.Probes = in.Probes
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersStateReporterSpec.
func (in *CBContainersStateReporterSpec) DeepCopy() *CBContainersStateReporterSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersStateReporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRIOSpec) DeepCopyInto(out *CRIOSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRIOSpec.
func (in *CRIOSpec) DeepCopy() *CRIOSpec {
	if in == nil {
		return nil
	}
	out := new(CRIOSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sContainerEngineSpec) DeepCopyInto(out *K8sContainerEngineSpec) {
	*out = *in
	out.CRIO = in.CRIO
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sContainerEngineSpec.
func (in *K8sContainerEngineSpec) DeepCopy() *K8sContainerEngineSpec {
	if in == nil {
		return nil
	}
	out := new(K8sContainerEngineSpec)
	in.DeepCopyInto(out)
	return out
}
