// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersCluster) DeepCopyInto(out *CBContainersCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersCluster.
func (in *CBContainersCluster) DeepCopy() *CBContainersCluster {
	if in == nil {
		return nil
	}
	out := new(CBContainersCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CBContainersCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersClusterApiGatewaySpec) DeepCopyInto(out *CBContainersClusterApiGatewaySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersClusterApiGatewaySpec.
func (in *CBContainersClusterApiGatewaySpec) DeepCopy() *CBContainersClusterApiGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersClusterApiGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersClusterList) DeepCopyInto(out *CBContainersClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CBContainersCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersClusterList.
func (in *CBContainersClusterList) DeepCopy() *CBContainersClusterList {
	if in == nil {
		return nil
	}
	out := new(CBContainersClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CBContainersClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersClusterSpec) DeepCopyInto(out *CBContainersClusterSpec) {
	*out = *in
	out.ApiGatewaySpec = in.ApiGatewaySpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersClusterSpec.
func (in *CBContainersClusterSpec) DeepCopy() *CBContainersClusterSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersClusterStatus) DeepCopyInto(out *CBContainersClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersClusterStatus.
func (in *CBContainersClusterStatus) DeepCopy() *CBContainersClusterStatus {
	if in == nil {
		return nil
	}
	out := new(CBContainersClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersGuardrails) DeepCopyInto(out *CBContainersGuardrails) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersGuardrails.
func (in *CBContainersGuardrails) DeepCopy() *CBContainersGuardrails {
	if in == nil {
		return nil
	}
	out := new(CBContainersGuardrails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CBContainersGuardrails) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersGuardrailsList) DeepCopyInto(out *CBContainersGuardrailsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CBContainersGuardrails, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersGuardrailsList.
func (in *CBContainersGuardrailsList) DeepCopy() *CBContainersGuardrailsList {
	if in == nil {
		return nil
	}
	out := new(CBContainersGuardrailsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CBContainersGuardrailsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersGuardrailsSpec) DeepCopyInto(out *CBContainersGuardrailsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersGuardrailsSpec.
func (in *CBContainersGuardrailsSpec) DeepCopy() *CBContainersGuardrailsSpec {
	if in == nil {
		return nil
	}
	out := new(CBContainersGuardrailsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CBContainersGuardrailsStatus) DeepCopyInto(out *CBContainersGuardrailsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CBContainersGuardrailsStatus.
func (in *CBContainersGuardrailsStatus) DeepCopy() *CBContainersGuardrailsStatus {
	if in == nil {
		return nil
	}
	out := new(CBContainersGuardrailsStatus)
	in.DeepCopyInto(out)
	return out
}
