// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor.proto

package monitor

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceHealthReport_Kind int32

const (
	ServiceHealthReport_DEPLOYMENT ServiceHealthReport_Kind = 0
	ServiceHealthReport_DAEMONSET  ServiceHealthReport_Kind = 1
)

var ServiceHealthReport_Kind_name = map[int32]string{
	0: "DEPLOYMENT",
	1: "DAEMONSET",
}

var ServiceHealthReport_Kind_value = map[string]int32{
	"DEPLOYMENT": 0,
	"DAEMONSET":  1,
}

func (x ServiceHealthReport_Kind) String() string {
	return proto.EnumName(ServiceHealthReport_Kind_name, int32(x))
}

func (ServiceHealthReport_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{4, 0}
}

type ContainerSpec struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerSpec) Reset()         { *m = ContainerSpec{} }
func (m *ContainerSpec) String() string { return proto.CompactTextString(m) }
func (*ContainerSpec) ProtoMessage()    {}
func (*ContainerSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{0}
}

func (m *ContainerSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerSpec.Unmarshal(m, b)
}
func (m *ContainerSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerSpec.Marshal(b, m, deterministic)
}
func (m *ContainerSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerSpec.Merge(m, src)
}
func (m *ContainerSpec) XXX_Size() int {
	return xxx_messageInfo_ContainerSpec.Size(m)
}
func (m *ContainerSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerSpec proto.InternalMessageInfo

func (m *ContainerSpec) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type ReplicaSpec struct {
	Containers           map[string]*ContainerSpec `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ReplicaSpec) Reset()         { *m = ReplicaSpec{} }
func (m *ReplicaSpec) String() string { return proto.CompactTextString(m) }
func (*ReplicaSpec) ProtoMessage()    {}
func (*ReplicaSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{1}
}

func (m *ReplicaSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaSpec.Unmarshal(m, b)
}
func (m *ReplicaSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaSpec.Marshal(b, m, deterministic)
}
func (m *ReplicaSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaSpec.Merge(m, src)
}
func (m *ReplicaSpec) XXX_Size() int {
	return xxx_messageInfo_ReplicaSpec.Size(m)
}
func (m *ReplicaSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaSpec proto.InternalMessageInfo

func (m *ReplicaSpec) GetContainers() map[string]*ContainerSpec {
	if m != nil {
		return m.Containers
	}
	return nil
}

type ReplicaHealth struct {
	Node                 string       `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Spec                 *ReplicaSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status               []byte       `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplicaHealth) Reset()         { *m = ReplicaHealth{} }
func (m *ReplicaHealth) String() string { return proto.CompactTextString(m) }
func (*ReplicaHealth) ProtoMessage()    {}
func (*ReplicaHealth) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{2}
}

func (m *ReplicaHealth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaHealth.Unmarshal(m, b)
}
func (m *ReplicaHealth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaHealth.Marshal(b, m, deterministic)
}
func (m *ReplicaHealth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaHealth.Merge(m, src)
}
func (m *ReplicaHealth) XXX_Size() int {
	return xxx_messageInfo_ReplicaHealth.Size(m)
}
func (m *ReplicaHealth) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaHealth.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaHealth proto.InternalMessageInfo

func (m *ReplicaHealth) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *ReplicaHealth) GetSpec() *ReplicaSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *ReplicaHealth) GetStatus() []byte {
	if m != nil {
		return m.Status
	}
	return nil
}

type ServiceSpec struct {
	Replicas             int32                     `protobuf:"varint,1,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Containers           map[string]*ContainerSpec `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ServiceSpec) Reset()         { *m = ServiceSpec{} }
func (m *ServiceSpec) String() string { return proto.CompactTextString(m) }
func (*ServiceSpec) ProtoMessage()    {}
func (*ServiceSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{3}
}

func (m *ServiceSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceSpec.Unmarshal(m, b)
}
func (m *ServiceSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceSpec.Marshal(b, m, deterministic)
}
func (m *ServiceSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceSpec.Merge(m, src)
}
func (m *ServiceSpec) XXX_Size() int {
	return xxx_messageInfo_ServiceSpec.Size(m)
}
func (m *ServiceSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceSpec proto.InternalMessageInfo

func (m *ServiceSpec) GetReplicas() int32 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func (m *ServiceSpec) GetContainers() map[string]*ContainerSpec {
	if m != nil {
		return m.Containers
	}
	return nil
}

type ServiceHealthReport struct {
	Kind                 ServiceHealthReport_Kind  `protobuf:"varint,1,opt,name=kind,proto3,enum=monitor.ServiceHealthReport_Kind" json:"kind,omitempty"`
	Spec                 *ServiceSpec              `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status               []byte                    `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Replicas             map[string]*ReplicaHealth `protobuf:"bytes,4,rep,name=replicas,proto3" json:"replicas,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ServiceHealthReport) Reset()         { *m = ServiceHealthReport{} }
func (m *ServiceHealthReport) String() string { return proto.CompactTextString(m) }
func (*ServiceHealthReport) ProtoMessage()    {}
func (*ServiceHealthReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{4}
}

func (m *ServiceHealthReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceHealthReport.Unmarshal(m, b)
}
func (m *ServiceHealthReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceHealthReport.Marshal(b, m, deterministic)
}
func (m *ServiceHealthReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceHealthReport.Merge(m, src)
}
func (m *ServiceHealthReport) XXX_Size() int {
	return xxx_messageInfo_ServiceHealthReport.Size(m)
}
func (m *ServiceHealthReport) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceHealthReport.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceHealthReport proto.InternalMessageInfo

func (m *ServiceHealthReport) GetKind() ServiceHealthReport_Kind {
	if m != nil {
		return m.Kind
	}
	return ServiceHealthReport_DEPLOYMENT
}

func (m *ServiceHealthReport) GetSpec() *ServiceSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *ServiceHealthReport) GetStatus() []byte {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ServiceHealthReport) GetReplicas() map[string]*ReplicaHealth {
	if m != nil {
		return m.Replicas
	}
	return nil
}

type HealthReport struct {
	Account              string                          `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Domain               string                          `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Services             map[string]*ServiceHealthReport `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *HealthReport) Reset()         { *m = HealthReport{} }
func (m *HealthReport) String() string { return proto.CompactTextString(m) }
func (*HealthReport) ProtoMessage()    {}
func (*HealthReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{5}
}

func (m *HealthReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthReport.Unmarshal(m, b)
}
func (m *HealthReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthReport.Marshal(b, m, deterministic)
}
func (m *HealthReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthReport.Merge(m, src)
}
func (m *HealthReport) XXX_Size() int {
	return xxx_messageInfo_HealthReport.Size(m)
}
func (m *HealthReport) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthReport.DiscardUnknown(m)
}

var xxx_messageInfo_HealthReport proto.InternalMessageInfo

func (m *HealthReport) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *HealthReport) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *HealthReport) GetServices() map[string]*ServiceHealthReport {
	if m != nil {
		return m.Services
	}
	return nil
}

type HealthReportReply struct {
	Ack                  bool     `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthReportReply) Reset()         { *m = HealthReportReply{} }
func (m *HealthReportReply) String() string { return proto.CompactTextString(m) }
func (*HealthReportReply) ProtoMessage()    {}
func (*HealthReportReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_44174b7b2a306b71, []int{6}
}

func (m *HealthReportReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthReportReply.Unmarshal(m, b)
}
func (m *HealthReportReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthReportReply.Marshal(b, m, deterministic)
}
func (m *HealthReportReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthReportReply.Merge(m, src)
}
func (m *HealthReportReply) XXX_Size() int {
	return xxx_messageInfo_HealthReportReply.Size(m)
}
func (m *HealthReportReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthReportReply.DiscardUnknown(m)
}

var xxx_messageInfo_HealthReportReply proto.InternalMessageInfo

func (m *HealthReportReply) GetAck() bool {
	if m != nil {
		return m.Ack
	}
	return false
}

func init() {
	proto.RegisterEnum("monitor.ServiceHealthReport_Kind", ServiceHealthReport_Kind_name, ServiceHealthReport_Kind_value)
	proto.RegisterType((*ContainerSpec)(nil), "monitor.ContainerSpec")
	proto.RegisterType((*ReplicaSpec)(nil), "monitor.ReplicaSpec")
	proto.RegisterMapType((map[string]*ContainerSpec)(nil), "monitor.ReplicaSpec.ContainersEntry")
	proto.RegisterType((*ReplicaHealth)(nil), "monitor.ReplicaHealth")
	proto.RegisterType((*ServiceSpec)(nil), "monitor.ServiceSpec")
	proto.RegisterMapType((map[string]*ContainerSpec)(nil), "monitor.ServiceSpec.ContainersEntry")
	proto.RegisterType((*ServiceHealthReport)(nil), "monitor.ServiceHealthReport")
	proto.RegisterMapType((map[string]*ReplicaHealth)(nil), "monitor.ServiceHealthReport.ReplicasEntry")
	proto.RegisterType((*HealthReport)(nil), "monitor.HealthReport")
	proto.RegisterMapType((map[string]*ServiceHealthReport)(nil), "monitor.HealthReport.ServicesEntry")
	proto.RegisterType((*HealthReportReply)(nil), "monitor.HealthReportReply")
}

func init() { proto.RegisterFile("monitor.proto", fileDescriptor_44174b7b2a306b71) }

var fileDescriptor_44174b7b2a306b71 = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x77, 0xda, 0x74, 0xdb, 0xbe, 0x6e, 0xd6, 0x3a, 0xae, 0x4b, 0x08, 0x1e, 0x6a, 0x74,
	0x21, 0x88, 0xf4, 0x10, 0x11, 0xc4, 0x8b, 0x88, 0x8d, 0xac, 0x68, 0x77, 0x65, 0x5a, 0x0f, 0x7b,
	0x1c, 0x93, 0x41, 0x87, 0xa6, 0x33, 0x21, 0x99, 0x2e, 0xec, 0x57, 0xf2, 0x83, 0xf8, 0x01, 0x3c,
	0xfb, 0x61, 0xa4, 0x93, 0x49, 0xc8, 0x94, 0x5a, 0xf0, 0xe4, 0x6d, 0x5e, 0xe7, 0xbd, 0xf7, 0xff,
	0xff, 0x7f, 0x1d, 0x02, 0xee, 0x5a, 0x0a, 0xae, 0x64, 0x31, 0xcd, 0x0b, 0xa9, 0x24, 0xee, 0x9b,
	0x32, 0xb8, 0x00, 0xf7, 0x9d, 0x14, 0x8a, 0x72, 0xc1, 0x8a, 0x45, 0xce, 0x12, 0x7c, 0x06, 0x3d,
	0xbe, 0xa6, 0xdf, 0x98, 0x87, 0x26, 0x28, 0x1c, 0x92, 0xaa, 0x08, 0x7e, 0x20, 0x18, 0x11, 0x96,
	0x67, 0x3c, 0xa1, 0xba, 0x6b, 0x06, 0x90, 0xd4, 0x63, 0xa5, 0x87, 0x26, 0xdd, 0x70, 0x14, 0x3d,
	0x9d, 0xd6, 0x1a, 0xad, 0xce, 0x69, 0xb3, 0xbd, 0x8c, 0x85, 0x2a, 0xee, 0x48, 0x6b, 0xce, 0xff,
	0x02, 0xf7, 0x76, 0xae, 0xf1, 0x18, 0xba, 0x2b, 0x76, 0x67, 0xc4, 0xb7, 0x47, 0xfc, 0x1c, 0x7a,
	0xb7, 0x34, 0xdb, 0x30, 0xaf, 0x33, 0x41, 0xe1, 0x28, 0x3a, 0x6f, 0x54, 0x2c, 0xdf, 0xa4, 0x6a,
	0x7a, 0xdd, 0x79, 0x85, 0x02, 0x06, 0xae, 0x71, 0x70, 0xc9, 0x68, 0xa6, 0xbe, 0x63, 0x0c, 0x8e,
	0x90, 0x69, 0x1d, 0x49, 0x9f, 0x71, 0x08, 0x4e, 0x99, 0xb3, 0xc4, 0x6c, 0x3d, 0xdb, 0xe7, 0x9d,
	0xe8, 0x0e, 0x7c, 0x0e, 0xc7, 0xa5, 0xa2, 0x6a, 0x53, 0x7a, 0xdd, 0x09, 0x0a, 0x4f, 0x88, 0xa9,
	0x82, 0x9f, 0x08, 0x46, 0x0b, 0x56, 0xdc, 0xf2, 0x84, 0x69, 0x26, 0x3e, 0x0c, 0x8a, 0x6a, 0xb8,
	0xd4, 0x4a, 0x3d, 0xd2, 0xd4, 0x3b, 0xbc, 0x3a, 0x3b, 0xbc, 0x5a, 0x5b, 0xfe, 0x07, 0xaf, 0x5f,
	0x1d, 0x78, 0x60, 0x2c, 0x54, 0xc0, 0x08, 0xcb, 0x65, 0xa1, 0xf0, 0x4b, 0x70, 0x56, 0x5c, 0xa4,
	0x7a, 0xf9, 0x69, 0xf4, 0x78, 0xd7, 0x6e, 0xbb, 0x77, 0xfa, 0x91, 0x8b, 0x94, 0xe8, 0xf6, 0xbf,
	0x92, 0x6d, 0xa5, 0x3c, 0x4c, 0x16, 0xbf, 0x6f, 0x91, 0x74, 0x34, 0xab, 0x67, 0x07, 0xc5, 0xcd,
	0x7f, 0x66, 0x88, 0x35, 0xb3, 0xfe, 0xa2, 0x79, 0x08, 0xff, 0x4e, 0xcb, 0x7a, 0x41, 0x6d, 0x5a,
	0x17, 0xe0, 0x6c, 0xc3, 0xe2, 0x53, 0x80, 0x59, 0xfc, 0xf9, 0xd3, 0xf5, 0xcd, 0x3c, 0xbe, 0x5a,
	0x8e, 0x8f, 0xb0, 0x0b, 0xc3, 0xd9, 0xdb, 0x78, 0x7e, 0x7d, 0xb5, 0x88, 0x97, 0x63, 0x14, 0xfc,
	0x46, 0x70, 0x62, 0xd1, 0xf4, 0xa0, 0x4f, 0x93, 0x44, 0x6e, 0x84, 0x32, 0xfa, 0x75, 0xb9, 0xc5,
	0x90, 0xca, 0x35, 0xe5, 0x42, 0x9b, 0x18, 0x12, 0x53, 0xe1, 0x37, 0x30, 0x28, 0xab, 0xb4, 0x35,
	0x86, 0x27, 0x8d, 0x3d, 0x2b, 0xbf, 0x61, 0x52, 0xe7, 0xaf, 0x87, 0xfc, 0x1b, 0x70, 0xad, 0xab,
	0x3d, 0xf9, 0x23, 0x3b, 0xff, 0xa3, 0x43, 0x9c, 0x6d, 0x0a, 0xf7, 0xad, 0x2b, 0x96, 0x67, 0x7a,
	0x3d, 0x4d, 0x56, 0x7a, 0xfd, 0x80, 0x6c, 0x8f, 0xd1, 0x12, 0xfa, 0xf3, 0x6a, 0x21, 0xfe, 0x00,
	0xf8, 0x92, 0x8a, 0x34, 0xb3, 0xdf, 0xd8, 0xc3, 0xbd, 0x89, 0x7c, 0x7f, 0xef, 0xcf, 0x5a, 0x25,
	0x38, 0xfa, 0x7a, 0xac, 0x3f, 0x62, 0x2f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x8b, 0x7f,
	0xf5, 0xd5, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MonitorClient is the client API for Monitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorClient interface {
	HandleHealthReport(ctx context.Context, in *HealthReport, opts ...grpc.CallOption) (*HealthReportReply, error)
}

type monitorClient struct {
	cc *grpc.ClientConn
}

func NewMonitorClient(cc *grpc.ClientConn) MonitorClient {
	return &monitorClient{cc}
}

func (c *monitorClient) HandleHealthReport(ctx context.Context, in *HealthReport, opts ...grpc.CallOption) (*HealthReportReply, error) {
	out := new(HealthReportReply)
	err := c.cc.Invoke(ctx, "/monitor.Monitor/HandleHealthReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServer is the server API for Monitor service.
type MonitorServer interface {
	HandleHealthReport(context.Context, *HealthReport) (*HealthReportReply, error)
}

// UnimplementedMonitorServer can be embedded to have forward compatible implementations.
type UnimplementedMonitorServer struct {
}

func (*UnimplementedMonitorServer) HandleHealthReport(ctx context.Context, req *HealthReport) (*HealthReportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleHealthReport not implemented")
}

func RegisterMonitorServer(s *grpc.Server, srv MonitorServer) {
	s.RegisterService(&_Monitor_serviceDesc, srv)
}

func _Monitor_HandleHealthReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).HandleHealthReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor.Monitor/HandleHealthReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).HandleHealthReport(ctx, req.(*HealthReport))
	}
	return interceptor(ctx, in, info, handler)
}

var _Monitor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.Monitor",
	HandlerType: (*MonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleHealthReport",
			Handler:    _Monitor_HandleHealthReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor.proto",
}
