# permissions for end users to view cbcontainersagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cbcontainersagent-viewer-role
rules:
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainersagents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainersclusters/status
  verbs:
  - get
