# permissions for end users to edit cbcontainersguardrails.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cbcontainersguardrails-editor-role
rules:
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainersguardrails
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainersguardrails/status
  verbs:
  - get
