# permissions for end users to edit cbcontainersclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cbcontainerscluster-editor-role
rules:
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainersclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainersclusters/status
  verbs:
  - get
