# permissions for end users to view cbcontainershardenings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cbcontainershardening-viewer-role
rules:
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainershardenings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainershardenings/status
  verbs:
  - get
