# permissions for end users to view cbcontainersclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cbcontainerscluster-viewer-role
rules:
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainersclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainersclusters/status
  verbs:
  - get
