# permissions for end users to edit cbcontainershardenings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cbcontainershardening-editor-role
rules:
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainershardenings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainershardenings/status
  verbs:
  - get
