---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: monitor-role
rules:
  - apiGroups:
      - ""
      - apps
      - admissionregistration.k8s.io
    resources:
      - daemonsets
      - deployments
      - nodes
      - pods
      - replicasets
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: agent-node-role
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: enforcer-role
rules:
  - apiGroups:
      - apps
      - batch
    resources:
      - jobs
      - replicasets
    verbs:
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: image-scanning-role
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: runtime-resolver-role
rules:
  - apiGroups:
      - ""
      - discovery.k8s.io
      - apps
      - batch
    resources:
      - endpoints
      - endpointslices
      - jobs
      - nodes
      - pods
      - replicasets
      - services
    verbs:
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: state-reporter-role
rules:
  - apiGroups:
      - ""
      - apiextensions.k8s.io
      - apps
      - batch
      - extensions
      - networking.k8s.io
      - rbac
      - rbac.authorization.k8s.io
      - apps.openshift.io
      - route.openshift.io
    resources:
      - clusterrolebindings
      - cronjobs
      - customresourcedefinitions
      - daemonsets
      - deployments
      - ingresses
      - jobs
      - namespaces
      - nodes
      - pods
      - replicasets
      - replicationcontrollers
      - rolebindings
      - services
      - statefulsets
      - deploymentconfigs
      - routes
    verbs:
      - watch