
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - apps
  - ""
  resources:
  - daemonsets
  - deployments
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainersagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainersagents/finalizers
  verbs:
  - update
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainersagents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resourceNames:
  - cbcontainers-manager-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - '*'
