
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainersclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainersclusters/finalizers
  verbs:
  - update
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainersclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainersguardrails
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainersguardrails/finalizers
  verbs:
  - update
- apiGroups:
  - operator.containers.carbonblack.io
  resources:
  - cbcontainersguardrails/status
  verbs:
  - get
  - patch
  - update
