apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogeyJhdXRoIjogImIyTjBZWEpwYm1WdmNHVnlZWFJ2Y2pvMk5HSTFOMkkzTXkweU1qZzNMVFEwT1RJdFlqQm1aaTB4WkRnM05tTXdaalJqWXpBPSJ9fX0=
kind: Secret
metadata:
  name: cbcontainers-octarine-operator-public-registry-secret
  namespace: cbcontainers-dataplane
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: system
imagePullSecrets:
  - name: octarine-operator-public-registry-secret
