{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "octarine-operator.fullname" . }}
  labels:
{{ include "octarine-operator.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - '*'

# Guardrails cluster role
- apiGroups:
    - rbac.authorization.k8s.io
    - networking.k8s.io
    - apiextensions.k8s.io
    - extensions
    - rbac
    - batch
    - apps
    - ""
  resources:
    - namespaces
    - clusterrolebindings
    - services
    - networkpolicies
    - ingresses
    - rolebindings
    - cronjobs
    - jobs
    - replicationcontrollers
    - statefulsets
    - daemonsets
    - deployments
    - replicasets
    - pods
    - nodes
    - customresourcedefinitions
  verbs:
    - get
    - watch
    - list

# Nodeguard cluster role
- apiGroups:
    - batch
    - apps
    - ""
  resources:
    - services
    - jobs
    - deployments
    - replicasets
    - nodes
    - pods
  verbs:
    - get
    - watch
    - list
{{- end -}}
