apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: octarines.operator.octarinesec.com
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: operator.octarinesec.com
  names:
    kind: Octarine
    listKind: OctarineList
    plural: octarines
    singular: octarine
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
