# CRD definition for Helm 2
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: octarines.operator.octarinesec.com
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: operator.octarinesec.com
  names:
    kind: Octarine
    listKind: OctarineList
    plural: octarines
    singular: octarine
  scope: Namespaced
  subresources:
    status: {}
  versions:
    - name: v1alpha1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      description: Octarine is the Schema for the octarines API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
          of an object. Servers should convert recognized schemas to the latest
          internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
          object represents. Servers may infer this from the endpoint the client
          submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: OctarineSpec defines the desired state of Octarine
          type: object
        status:
          description: OctarineStatus defines the observed state of Octarine
          type: object
      type: object