{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "octarine-operator.serviceAccountName" . }}
  labels:
{{ include "octarine-operator.labels" . | indent 4 }}
imagePullSecrets:
  - name: {{ include "octarine-operator.imagePullSecret.name" . }}
{{- end -}}
