// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/cbcontainers-operator/cbcontainers/processors (interfaces: APIGateway)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vmware/cbcontainers-operator/cbcontainers/models"
)

// MockAPIGateway is a mock of APIGateway interface.
type MockAPIGateway struct {
	ctrl     *gomock.Controller
	recorder *MockAPIGatewayMockRecorder
}

// MockAPIGatewayMockRecorder is the mock recorder for MockAPIGateway.
type MockAPIGatewayMockRecorder struct {
	mock *MockAPIGateway
}

// NewMockAPIGateway creates a new mock instance.
func NewMockAPIGateway(ctrl *gomock.Controller) *MockAPIGateway {
	mock := &MockAPIGateway{ctrl: ctrl}
	mock.recorder = &MockAPIGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIGateway) EXPECT() *MockAPIGatewayMockRecorder {
	return m.recorder
}

// GetRegistrySecret mocks base method.
func (m *MockAPIGateway) GetRegistrySecret() (*models.RegistrySecretValues, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrySecret")
	ret0, _ := ret[0].(*models.RegistrySecretValues)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrySecret indicates an expected call of GetRegistrySecret.
func (mr *MockAPIGatewayMockRecorder) GetRegistrySecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrySecret", reflect.TypeOf((*MockAPIGateway)(nil).GetRegistrySecret))
}

// RegisterCluster mocks base method.
func (m *MockAPIGateway) RegisterCluster() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterCluster")
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterCluster indicates an expected call of RegisterCluster.
func (mr *MockAPIGatewayMockRecorder) RegisterCluster() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterCluster", reflect.TypeOf((*MockAPIGateway)(nil).RegisterCluster))
}
