apiVersion: v1
kind: ServiceAccount
metadata:
  name: state-reporter
  namespace: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: enforcer
  namespace: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor
  namespace: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-scanning
  namespace: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runtime-resolver
  namespace: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-node
  namespace: system

