apiVersion: v1
kind: ServiceAccount
metadata:
  name: state-reporter
  namespace: system
imagePullSecrets:
  - name: cbcontainers-operator-public-registry-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: enforcer
  namespace: system
imagePullSecrets:
  - name: cbcontainers-operator-public-registry-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor
  namespace: system
imagePullSecrets:
  - name: cbcontainers-operator-public-registry-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-scanning
  namespace: system
imagePullSecrets:
  - name: cbcontainers-operator-public-registry-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: runtime-resolver
  namespace: system
imagePullSecrets:
  - name: cbcontainers-operator-public-registry-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-node
  namespace: system
imagePullSecrets:
  - name: cbcontainers-operator-public-registry-secret

