apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: cbcontainers.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CBContainersAgent is the Schema for the cbcontainersagents API
      displayName: CBContainers Agent
      kind: CBContainersAgent
      name: cbcontainersagents.operator.containers.carbonblack.io
      version: v1
  description: operator
  displayName: operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - security
  links:
  - name: Cbcontainers
    url: https://cbcontainers.domain
  maturity: alpha
  provider:
    name: Carbon Black
  version: 0.0.0
