apiVersion: operator.containers.carbonblack.io/v1
kind: CBContainersHardening
metadata:
  name: cbcontainershardening-sample
spec:
  # Add fields here
  version: "21.6"
  eventsGatewaySpec:
    host: https://test.com
