{{- /*
The Secret object will be rendered only if the accessToken value is provided.
this value is required in order for the agent components to work correctly
so not having the access token secret created here assumes that the user of the charts
created the secret in an alternative way
*/}}
{{- if .Values.companyCode -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cbcontainers-agent.company-code-name" .Values.components.cndr.companyCodeSecretName }}
  namespace: {{ default "cbcontainers-dataplane" .Values.agentNamespace }}
data:
  companyCode: {{ .Values.companyCode | b64enc }}
{{- end -}}
