apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cbcontainers-agent.access-token-name" .Values.accessTokenSecretName }}
  namespace: cbcontainers-dataplane
data:
  accessToken: {{ required "accessToken is required" .Values.accessToken | b64enc }}
