apiVersion: v1
imagePullSecrets:
  - name: cbcontainers-operator-public-registry-secret
kind: ServiceAccount
metadata:
  name: cbcontainers-agent-node
  namespace: { { default "cbcontainers-dataplane" .Values.namespace } }
---
apiVersion: v1
imagePullSecrets:
  - name: cbcontainers-operator-public-registry-secret
kind: ServiceAccount
metadata:
  name: cbcontainers-enforcer
  namespace: { { default "cbcontainers-dataplane" .Values.namespace } }
---
apiVersion: v1
imagePullSecrets:
  - name: cbcontainers-operator-public-registry-secret
kind: ServiceAccount
metadata:
  name: cbcontainers-image-scanning
  namespace: { { default "cbcontainers-dataplane" .Values.namespace } }
---
apiVersion: v1
imagePullSecrets:
  - name: cbcontainers-operator-public-registry-secret
kind: ServiceAccount
metadata:
  name: cbcontainers-monitor
  namespace: { { default "cbcontainers-dataplane" .Values.namespace } }
---
apiVersion: v1
imagePullSecrets:
  - name: cbcontainers-operator-public-registry-secret
kind: ServiceAccount
metadata:
  name: cbcontainers-runtime-resolver
  namespace: { { default "cbcontainers-dataplane" .Values.namespace } }
---
apiVersion: v1
imagePullSecrets:
  - name: cbcontainers-operator-public-registry-secret
kind: ServiceAccount
metadata:
  name: cbcontainers-state-reporter
  namespace: { { default "cbcontainers-dataplane" .Values.namespace } }
