{{- if .Values.imageCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "octarine.imagePullSecret.name" . }}
  labels:
{{ include "octarine.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "imagePullSecret.tpl" . }}
{{- end -}}