{{/*
Create nodeguard worker name
*/}}
{{- define "nodeguard.worker.name" -}}
{{- printf "%s-worker" (include "nodeguard.name" .) -}}
{{- end -}}

{{/*
Create nodeguard worker fullname
*/}}
{{- define "nodeguard.worker.fullname" -}}
{{- printf "%s-worker" (include "nodeguard.fullname" .) -}}
{{- end -}}

{{/*
worker labels
*/}}
{{- define "nodeguard.worker.labels" -}}
{{- template "nodeguard.labels.tpl" (list . (include "nodeguard.worker.name" .)) -}}
{{- end -}}

{{/*
Create configmap name for nodeguard worker env vars.
*/}}
{{- define "nodeguard.worker.configmap.env.fullname" -}}
{{-  printf "%s-env" (include "nodeguard.worker.fullname" .) -}}
{{- end -}}

  {{/*
Generate env vars for nodeguard worker.
Const env vars are taken from the values, dynamic env vars are generated here.
*/}}
{{- define "nodeguard.worker.env" -}}
{{ toYaml .Values.worker.env }}
OCTARINE_NODEGUARD_WORKER_SERVER_ADDRESS: {{ include "nodeguard.controller.service.address" . | quote }}
OCTARINE_NODEGUARD_WORKER_SERVER_PORT: {{ .Values.controller.service.port | quote }}
OCTARINE_NODEGUARD_WORKER_CONTAINER_INTERFACE_PREFIX: {{ .Values.worker.interfacePrefixes.container | quote }}
OCTARINE_NODEGUARD_WORKER_EXTERNAL_INTERFACE_PREFIX: {{ .Values.worker.interfacePrefixes.external | quote }}
OCTARINE_NODEGUARD_WORKER_PROBES_READINESS_PATH: {{ .Values.worker.probes.readinessPath }}
OCTARINE_NODEGUARD_WORKER_PROBES_LIVENESS_PATH: {{ .Values.worker.probes.livenessPath }}
{{- end -}}