{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nodeguard.fullname" . }}
  labels:
{{ include "nodeguard.labels" . | indent 4 }}
rules:
  - apiGroups:
      - batch
      - apps
      - ""
    resources:
      - services
      - jobs
      - deployments
      - replicasets
      - nodes
      - pods
    verbs:
      - get
      - watch
      - list
{{- end -}}