apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodeguard.controller.fullname" . }}
  labels:
{{ include "nodeguard.controller.labels" . | indent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "nodeguard.controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
