// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/cbcontainers-operator/config_applier (interfaces: ConfigurationAPI)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	config_applier "github.com/vmware/cbcontainers-operator/config_applier"
)

// MockConfigurationAPI is a mock of ConfigurationAPI interface.
type MockConfigurationAPI struct {
	ctrl     *gomock.Controller
	recorder *MockConfigurationAPIMockRecorder
}

// MockConfigurationAPIMockRecorder is the mock recorder for MockConfigurationAPI.
type MockConfigurationAPIMockRecorder struct {
	mock *MockConfigurationAPI
}

// NewMockConfigurationAPI creates a new mock instance.
func NewMockConfigurationAPI(ctrl *gomock.Controller) *MockConfigurationAPI {
	mock := &MockConfigurationAPI{ctrl: ctrl}
	mock.recorder = &MockConfigurationAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigurationAPI) EXPECT() *MockConfigurationAPIMockRecorder {
	return m.recorder
}

// GetConfigurationChanges mocks base method.
func (m *MockConfigurationAPI) GetConfigurationChanges() ([]config_applier.ConfigurationChange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigurationChanges")
	ret0, _ := ret[0].([]config_applier.ConfigurationChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigurationChanges indicates an expected call of GetConfigurationChanges.
func (mr *MockConfigurationAPIMockRecorder) GetConfigurationChanges() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigurationChanges", reflect.TypeOf((*MockConfigurationAPI)(nil).GetConfigurationChanges))
}

// UpdateConfigurationChangeStatus mocks base method.
func (m *MockConfigurationAPI) UpdateConfigurationChangeStatus(arg0 config_applier.ConfigurationChangeStatusUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfigurationChangeStatus", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfigurationChangeStatus indicates an expected call of UpdateConfigurationChangeStatus.
func (mr *MockConfigurationAPIMockRecorder) UpdateConfigurationChangeStatus(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfigurationChangeStatus", reflect.TypeOf((*MockConfigurationAPI)(nil).UpdateConfigurationChangeStatus), arg0)
}
