// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/cbcontainers-operator/cbcontainers/state/hardening/objects (interfaces: TlsSecretsValuesCreator)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vmware/cbcontainers-operator/cbcontainers/models"
	types "k8s.io/apimachinery/pkg/types"
)

// MockTlsSecretsValuesCreator is a mock of TlsSecretsValuesCreator interface.
type MockTlsSecretsValuesCreator struct {
	ctrl     *gomock.Controller
	recorder *MockTlsSecretsValuesCreatorMockRecorder
}

// MockTlsSecretsValuesCreatorMockRecorder is the mock recorder for MockTlsSecretsValuesCreator.
type MockTlsSecretsValuesCreatorMockRecorder struct {
	mock *MockTlsSecretsValuesCreator
}

// NewMockTlsSecretsValuesCreator creates a new mock instance.
func NewMockTlsSecretsValuesCreator(ctrl *gomock.Controller) *MockTlsSecretsValuesCreator {
	mock := &MockTlsSecretsValuesCreator{ctrl: ctrl}
	mock.recorder = &MockTlsSecretsValuesCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTlsSecretsValuesCreator) EXPECT() *MockTlsSecretsValuesCreatorMockRecorder {
	return m.recorder
}

// CreateTlsSecretsValues mocks base method.
func (m *MockTlsSecretsValuesCreator) CreateTlsSecretsValues(arg0 types.NamespacedName) (models.TlsSecretValues, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTlsSecretsValues", arg0)
	ret0, _ := ret[0].(models.TlsSecretValues)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTlsSecretsValues indicates an expected call of CreateTlsSecretsValues.
func (mr *MockTlsSecretsValuesCreatorMockRecorder) CreateTlsSecretsValues(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTlsSecretsValues", reflect.TypeOf((*MockTlsSecretsValuesCreator)(nil).CreateTlsSecretsValues), arg0)
}
