apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: octarine-dataplane
    octarine: ignore
  name: octarine-dataplane

---

apiVersion: v1
kind: Secret
metadata:
  name: octarine-operator-public-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogeyJhdXRoIjogImIyTjBZWEpwYm1WdmNHVnlZWFJ2Y2pvMk5HSTFOMkkzTXkweU1qZzNMVFEwT1RJdFlqQm1aaTB4WkRnM05tTXdaalJqWXpBPSJ9fX0=

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: octarine-dataplane
  name: octarine-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - octarine-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.octarinesec.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: octarine-dataplane
  name: octarine-operator
rules:
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
    - list
    - watch
    - update
- apiGroups:
    - admissionregistration.k8s.io
  resources:
    - validatingwebhookconfigurations
  verbs:
    - '*'
- apiGroups:
    - scheduling.k8s.io
  resources:
    - priorityclasses
  verbs:
    - '*'

# Guardrails cluster role
- apiGroups:
    - rbac.authorization.k8s.io
    - networking.k8s.io
    - apiextensions.k8s.io
    - extensions
    - rbac
    - batch
    - apps
    - ""
  resources:
    - namespaces
    - clusterrolebindings
    - services
    - networkpolicies
    - ingresses
    - rolebindings
    - cronjobs
    - jobs
    - replicationcontrollers
    - statefulsets
    - daemonsets
    - deployments
    - replicasets
    - pods
    - nodes
    - customresourcedefinitions
  verbs:
    - get
    - watch
    - list

# Nodeguard cluster role
- apiGroups:
    - batch
    - apps
    - ""
  resources:
    - services
    - jobs
    - deployments
    - replicasets
    - nodes
    - pods
  verbs:
    - get
    - watch
    - list

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: octarine-dataplane
  name: octarine-operator
subjects:
- kind: ServiceAccount
  name: octarine-operator
roleRef:
  kind: Role
  name: octarine-operator
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: octarine-dataplane
  name: octarine-operator
imagePullSecrets:
  - name: octarine-operator-registry-secret
  - name: octarine-operator-public-registry-secret

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: octarine-dataplane
  name: octarine-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: octarine-operator
  template:
    metadata:
      labels:
        name: octarine-operator
    spec:
      serviceAccountName: octarine-operator
      containers:
        - name: octarine-operator
          image: octarinesec/octarine-operator:grc351
          imagePullPolicy: Always
          args:
            - --zap-level=1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "octarine-operator"
            - name: IMAGE_PULL_SECRET_NAME
              value: "octarine-operator-registry-secret"
            - name: SERVICE_ACCOUNT_NAME
              value: "octarine-operator"

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: octarine-dataplane
  name: octarine-operator
subjects:
- kind: ServiceAccount
  namespace: octarine-dataplane
  name: octarine-operator
roleRef:
  kind: ClusterRole
  name: octarine-operator
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  namespace: octarine-dataplane
  name: octarines.operator.octarinesec.com
spec:
  group: operator.octarinesec.com
  names:
    kind: Octarine
    listKind: OctarineList
    plural: octarines
    singular: octarine
  scope: Namespaced
  subresources:
    status: {}
  versions:
    - name: v1alpha1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      description: Octarine is the Schema for the octarines API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
          of an object. Servers should convert recognized schemas to the latest
          internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
          object represents. Servers may infer this from the endpoint the client
          submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: OctarineSpec defines the desired state of Octarine
          type: object
        status:
          description: OctarineStatus defines the observed state of Octarine
          type: object
      type: object