// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/cbcontainers-operator/controllers (interfaces: Gateway)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vmware/cbcontainers-operator/cbcontainers/models"
)

// MockGateway is a mock of Gateway interface.
type MockGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayMockRecorder
}

// MockGatewayMockRecorder is the mock recorder for MockGateway.
type MockGatewayMockRecorder struct {
	mock *MockGateway
}

// NewMockGateway creates a new mock instance.
func NewMockGateway(ctrl *gomock.Controller) *MockGateway {
	mock := &MockGateway{ctrl: ctrl}
	mock.recorder = &MockGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGateway) EXPECT() *MockGatewayMockRecorder {
	return m.recorder
}

// GetCompatibilityMatrixEntryFor mocks base method.
func (m *MockGateway) GetCompatibilityMatrixEntryFor(arg0 string) (*models.OperatorCompatibility, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompatibilityMatrixEntryFor", arg0)
	ret0, _ := ret[0].(*models.OperatorCompatibility)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompatibilityMatrixEntryFor indicates an expected call of GetCompatibilityMatrixEntryFor.
func (mr *MockGatewayMockRecorder) GetCompatibilityMatrixEntryFor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompatibilityMatrixEntryFor", reflect.TypeOf((*MockGateway)(nil).GetCompatibilityMatrixEntryFor), arg0)
}
