// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/cbcontainers-operator/controllers (interfaces: HardeningStateApplier)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/vmware/cbcontainers-operator/api/v1"
	options "github.com/vmware/cbcontainers-operator/cbcontainers/state/applyment/options"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockHardeningStateApplier is a mock of HardeningStateApplier interface.
type MockHardeningStateApplier struct {
	ctrl     *gomock.Controller
	recorder *MockHardeningStateApplierMockRecorder
}

// MockHardeningStateApplierMockRecorder is the mock recorder for MockHardeningStateApplier.
type MockHardeningStateApplierMockRecorder struct {
	mock *MockHardeningStateApplier
}

// NewMockHardeningStateApplier creates a new mock instance.
func NewMockHardeningStateApplier(ctrl *gomock.Controller) *MockHardeningStateApplier {
	mock := &MockHardeningStateApplier{ctrl: ctrl}
	mock.recorder = &MockHardeningStateApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHardeningStateApplier) EXPECT() *MockHardeningStateApplierMockRecorder {
	return m.recorder
}

// ApplyDesiredState mocks base method.
func (m *MockHardeningStateApplier) ApplyDesiredState(arg0 context.Context, arg1 *v1.CBContainersHardening, arg2 client.Client, arg3 options.OwnerSetter) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyDesiredState", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyDesiredState indicates an expected call of ApplyDesiredState.
func (mr *MockHardeningStateApplierMockRecorder) ApplyDesiredState(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyDesiredState", reflect.TypeOf((*MockHardeningStateApplier)(nil).ApplyDesiredState), arg0, arg1, arg2, arg3)
}
