// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/cbcontainers-operator/controllers (interfaces: StateApplier)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/vmware/cbcontainers-operator/api/v1"
	models "github.com/vmware/cbcontainers-operator/cbcontainers/models"
	options "github.com/vmware/cbcontainers-operator/cbcontainers/state/applyment/options"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockStateApplier is a mock of StateApplier interface.
type MockStateApplier struct {
	ctrl     *gomock.Controller
	recorder *MockStateApplierMockRecorder
}

// MockStateApplierMockRecorder is the mock recorder for MockStateApplier.
type MockStateApplierMockRecorder struct {
	mock *MockStateApplier
}

// NewMockStateApplier creates a new mock instance.
func NewMockStateApplier(ctrl *gomock.Controller) *MockStateApplier {
	mock := &MockStateApplier{ctrl: ctrl}
	mock.recorder = &MockStateApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateApplier) EXPECT() *MockStateApplierMockRecorder {
	return m.recorder
}

// ApplyDesiredState mocks base method.
func (m *MockStateApplier) ApplyDesiredState(arg0 context.Context, arg1 *v1.CBContainersAgentSpec, arg2 *models.RegistrySecretValues, arg3 options.OwnerSetter) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyDesiredState", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyDesiredState indicates an expected call of ApplyDesiredState.
func (mr *MockStateApplierMockRecorder) ApplyDesiredState(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyDesiredState", reflect.TypeOf((*MockStateApplier)(nil).ApplyDesiredState), arg0, arg1, arg2, arg3)
}

// ShouldProcessEvent mocks base method.
func (m *MockStateApplier) ShouldProcessEvent(arg0 client.Object) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldProcessEvent", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldProcessEvent indicates an expected call of ShouldProcessEvent.
func (mr *MockStateApplierMockRecorder) ShouldProcessEvent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldProcessEvent", reflect.TypeOf((*MockStateApplier)(nil).ShouldProcessEvent), arg0)
}
