# Legacy support for v1beta1 by removing the CRDs that use the newer v1 version
---

$patch: delete
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cbcontainersagents.operator.containers.carbonblack.io