name: Build and publish services

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "*"
      -

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Push CBContainers operator
        run: ls
