name: Build and publish services

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            octarine-operator
          flavor: |
            latest=false
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4
      - name: Setup Operator SDK
        run: |
          mkdir /tmp/operator-sdk
          git clone -b v1.32.0 https://github.com/operator-framework/operator-sdk /tmp/operator-sdk
          cd /tmp/operator-sdk
          make install
          cd -
      - run: make generate
      - run: make manifests
      - run: make test
      - name: Build and push
        if: github.ref == 'refs/heads/master'
        run: make docker-build docker-push IMG=cbartifactory/${{ steps.meta.outputs.tags }} VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
      - name: Create and push chart
        run: |
          VERSION='1.2.3'
          cd ${{ github.workspace }}/charts/cbcontainers-operator/cbcontainers-operator-chart
          helm package . --version $VERSION --app-version $VERSION
          helm push *.tgz oci://registry-1.docker.io/cbartifactory
          cd ${{ github.workspace }}/charts/cbcontainers-agent/cbcontainers-agent-chart
          helm package . --version $VERSION --app-version $VERSION
          helm push *.tgz oci://registry-1.docker.io/cbartifactory
