name: Build and publish services

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "*"
      -

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - id: docker-tag
        uses: yuya-takeyama/docker-tag-from-github-ref-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build & Push CBContainers operator
        run: ls