name: Build and publish services

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker pull gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
      - run: docker tag gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0 cbartifactory/kube-rbac-proxy:v0.13.0
      - run: docker push cbartifactory/kube-rbac-proxy:v0.13.0
