name: Build and publish services

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Setup Operator SDK
        run: |
          mkdir /tmp/operator-sdk
          git clone -b v1.25.2 https://github.com/operator-framework/operator-sdk /tmp/operator-sdk
          cd /tmp/operator-sdk
          make install
          cd -
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.1.1
      - run: make generate
      - run: make manifests
      - run: make test
      - name: Build and push
        run: make docker-build docker-push IMG=cbartifactory/octarine-operator:${{ steps.meta.outputs.tags }} VERSION=${{ steps.meta.outputs.tags }}
