name: Build and publish services

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "*"
      -

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: make generate
      - run: make manifests
      - name: Build and push
        run: make docker-build docker-push IMG=cbartifactory/octarine-operator:test
