// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/cbcontainers-operator/cbcontainers/processors/cluster (interfaces: Gateway)

// Package mocks is a generated GoMock package.
package mocks

import (
	rsa "crypto/rsa"
	tls "crypto/tls"
	x509 "crypto/x509"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/vmware/cbcontainers-operator/cbcontainers/models"
)

// MockGateway is a mock of Gateway interface.
type MockGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayMockRecorder
}

// MockGatewayMockRecorder is the mock recorder for MockGateway.
type MockGatewayMockRecorder struct {
	mock *MockGateway
}

// NewMockGateway creates a new mock instance.
func NewMockGateway(ctrl *gomock.Controller) *MockGateway {
	mock := &MockGateway{ctrl: ctrl}
	mock.recorder = &MockGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGateway) EXPECT() *MockGatewayMockRecorder {
	return m.recorder
}

// GetCertificates mocks base method.
func (m *MockGateway) GetCertificates(arg0 string, arg1 *rsa.PrivateKey) (*x509.CertPool, *tls.Certificate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCertificates", arg0, arg1)
	ret0, _ := ret[0].(*x509.CertPool)
	ret1, _ := ret[1].(*tls.Certificate)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCertificates indicates an expected call of GetCertificates.
func (mr *MockGatewayMockRecorder) GetCertificates(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCertificates", reflect.TypeOf((*MockGateway)(nil).GetCertificates), arg0, arg1)
}

// GetRegistrySecret mocks base method.
func (m *MockGateway) GetRegistrySecret() (*models.RegistrySecretValues, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrySecret")
	ret0, _ := ret[0].(*models.RegistrySecretValues)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrySecret indicates an expected call of GetRegistrySecret.
func (mr *MockGatewayMockRecorder) GetRegistrySecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrySecret", reflect.TypeOf((*MockGateway)(nil).GetRegistrySecret))
}

// RegisterCluster mocks base method.
func (m *MockGateway) RegisterCluster() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterCluster")
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterCluster indicates an expected call of RegisterCluster.
func (mr *MockGatewayMockRecorder) RegisterCluster() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterCluster", reflect.TypeOf((*MockGateway)(nil).RegisterCluster))
}
