{{- $imageTag := default .Values.global.octarine.version .Values.image.tag -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guardrails.fullname" . }}
  labels:
{{ include "guardrails.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "guardrails.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: {{ .Values.prometheus.scrape | quote }}
        prometheus.io/port: {{ .Values.prometheus.port | quote }}
      labels:
        app.kubernetes.io/name: {{ include "guardrails.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "guardrails.serviceAccountName" . }}
      priorityClassName: {{ include "octarine.priorityClass.name" . }}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - "/guardrail"
            - "-logtostderr=true"
          env:
            {{ include "octarine.common.env" . | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "guardrails.configmap.env.fullname" . }}
            {{ include "octarine.common.envFrom" . | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ $imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 443
            - name: probes-port
              containerPort: {{ .Values.probes.port }}
            - name: prometheus
              containerPort: {{ .Values.prometheus.port }}
          livenessProbe:
            periodSeconds: 30
            initialDelaySeconds: 5
            httpGet:
              path: /alive
              port: probes-port
          readinessProbe:
            periodSeconds: 30
            httpGet:
              path: /ready
              port: probes-port
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: cert
              mountPath: /etc/octarine-certificates
      volumes:
        - name: cert
          secret:
            secretName: {{ include "guardrails.tls.secret.name" . }}
            defaultMode: 420
            optional: true
